### ISSUE TITLE
Controlled checked value of checkbox not working when you want to uncheck again

### ISSUE THREAD

**Issue by daphnesmit** [accessible-ui/checkbox#6]
Dear jared! 
I use your libs a lot since I like that they are fully accessible. So great work!

When making a bunch of controlled checkboxes I noticed that when I want to control the checked value from outside I need to press 2 times on the checkbox afterwards to uncheck the checkbox. I highly suspect that useSwitch is maybe not handling the toggling correctly. (we use a similiar thing called https://www.npmjs.com/package/use-binding)

I made  codesandbox for this to demonstrate the issue.

https://codesandbox.io/s/admiring-aryabhata-1wy47?file=/src/App.tsx

If you press the button to check the checkbox and try to uncheck it using the checkbox itself you see you need to press to times. 
Meanwhile I will try to see if I can find the issue!

**Comment by daphnesmit** [comment]
@jaredLunde could you check pr of updated switch :)!

**Comment by jaredLunde** [comment]
There was one other funky thing that was going on, but I think I fixed it yesterday. Can you make sure you've got the latest version installed?
